import React,{useEffect,useMemo,useState}from "react";
import{createRoot}from"react-dom/client";
import{createClient}from"@supabase/supabase-js";
import"./style.css";import"./enhancements.css";import"./admin-ui.css";

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
const logoUrl=`${import.meta.env.BASE_URL}logo-yayasan.svg`,publicUrl=import.meta.env.BASE_URL;
const emptyArticle={title:"",subtitle:"",slug:"",content:"",status:"draft",cover_image_url:"",references_text:"",category_id:""};
const emptyAnnouncement={title:"",content:"",type:"text",banner_image_url:"",is_active:true,start_date:"",end_date:""};
const emptyProfile={name:"Yayasan Bina Tandang Nurul Falah",tagline:"",short_description:"",full_description:"",vision:"",mission:"",address:"",phone:"",email:"",social_links:"{}"};
const emptyProgram={title:"",slug:"",short_description:"",content:"",image_url:"",category_id:"",is_featured:true,is_active:true,order_index:0};
const emptyEvent={title:"",slug:"",description:"",location:"",start_at:"",end_at:"",image_url:"",category_id:"",is_published:true};
const emptyAlbum={title:"",slug:"",description:"",cover_image_url:"",is_published:true};
const ratios={"16:9":[1280,720],"4:3":[1200,900],"1:1":[1000,1000],"3:4":[900,1200]};
const imageTypes=["image/jpeg","image/png","image/webp","image/gif"];

async function cropImage(file,ratio="16:9",zoom=1){
 const src=URL.createObjectURL(file),img=new Image();
 try{await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=src});const[w,h]=ratios[ratio]||ratios["16:9"],scale=Math.max(w/img.naturalWidth,h/img.naturalHeight)*zoom,sw=w/scale,sh=h/scale,sx=(img.naturalWidth-sw)/2,sy=(img.naturalHeight-sh)/2,c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(img,sx,sy,sw,sh,0,0,w,h);return await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(new File([b],`yayasan-${Date.now()}.webp`,{type:"image/webp"})):reject(new Error("Gagal memproses foto")),"image/webp",.9))}finally{URL.revokeObjectURL(src)}}

function Preview({title,image,subtitle,content,type="Konten",meta=""}){return <aside className="live-preview card"><div className="preview-head"><span>{type}</span><strong>Live Preview</strong></div><div className="preview-card"><div className="preview-media">{image?<img src={image} alt="Preview"/>:<div className="preview-empty"><img src={logoUrl} alt="Logo Yayasan"/><span>Belum ada foto</span></div>}</div><div className="preview-body"><small>{subtitle||"Yayasan Bina Tandang Nurul Falah"}</small><h3>{title||"Judul akan tampil di sini"}</h3>{meta&&<div className="preview-meta">{meta}</div>}<p>{(content||"Isi konten di form untuk melihat pratinjau.").slice(0,320)}{content&&content.length>320?"…":""}</p></div></div></aside>}

function ImageField({label,value,onChange,ratio="16:9",upload,help="Pilih foto, atur rasio dan zoom, lihat preview, lalu gunakan foto."}){
 const[file,setFile]=useState(null),[preview,setPreview]=useState(value||""),[r,setR]=useState(ratio),[zoom,setZoom]=useState(1),[busy,setBusy]=useState(false);
 useEffect(()=>setPreview(value||""),[value]);
 useEffect(()=>()=>{if(preview?.startsWith("blob:"))URL.revokeObjectURL(preview)},[preview]);
 async function usePhoto(){if(!file)return;setBusy(true);try{const url=await upload(file,label.toLowerCase().replace(/[^a-z0-9]+/gi,"-"),r,zoom);if(url){onChange(url);setPreview(url);setFile(null)}}finally{setBusy(false)}}
 function choose(e){const f=e.target.files?.[0];if(!f)return;if(!imageTypes.includes(f.type)||f.size>12*1024*1024){return}setFile(f);setPreview(URL.createObjectURL(f))}
 return <div className="image-field"><div className="image-field-head"><label>{label}<small>{help}</small></label></div><div className="image-grid"><div className="image-controls"><label className="file-picker"><span>📷 Pilih foto</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={choose}/></label><select value={r} onChange={e=>setR(e.target.value)}><option value="16:9">16:9 — Banner / Artikel</option><option value="4:3">4:3 — Agenda / Galeri</option><option value="1:1">1:1 — Kotak</option><option value="3:4">3:4 — Potret</option></select><label>Zoom <input type="range" min="1" max="2.5" step=".05" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/><span>{zoom.toFixed(2)}×</span></label><div className="image-actions">{file&&<button type="button" onClick={usePhoto} disabled={busy}>{busy?"Memproses…":"✓ Gunakan Foto Ini"}</button>}{value&&<button type="button" className="secondary" onClick={()=>{onChange("");setFile(null);setPreview("")}}>Hapus Foto</button>}</div></div><div className="image-preview"><div className={`crop-frame ratio-${r.replace(":","x")}`}><img src={preview||logoUrl} alt="Preview crop"/></div><small>{file?"Preview foto yang dipilih — belum diunggah":"Preview foto yang akan diterbitkan"}</small></div></div></div>}

function GalleryUploader({upload,onAdded}){
 const[files,setFiles]=useState([]),[ratio,setRatio]=useState("4:3"),[zoom,setZoom]=useState(1),[busy,setBusy]=useState(false);
 useEffect(()=>()=>files.forEach(x=>URL.revokeObjectURL(x.preview)),[files]);
 function choose(e){const picked=Array.from(e.target.files||[]).filter(f=>imageTypes.includes(f.type)&&f.size<=12*1024*1024);setFiles(picked.map(file=>({file,preview:URL.createObjectURL(file)})))}
 async function uploadAll(){if(!files.length)return;setBusy(true);try{for(const item of files){const url=await upload(item.file,"galeri",ratio,zoom);if(url)await onAdded(url,item.file.name.replace(/\.[^.]+$/,""))}setFiles([])}finally{setBusy(false)}}
 return <div className="gallery-uploader"><div className="uploader-head"><div><h3>Upload foto galeri</h3><p>Pilih beberapa foto. Semua foto dipreview dan dipotong sebelum disimpan.</p></div><label className="file-picker"><span>📷 Pilih foto</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple onChange={choose}/></label></div>{files.length>0&&<><div className="uploader-tools"><select value={ratio} onChange={e=>setRatio(e.target.value)}><option value="4:3">4:3 — Galeri</option><option value="16:9">16:9 — Landscape</option><option value="1:1">1:1 — Kotak</option><option value="3:4">3:4 — Potret</option></select><label>Zoom <input type="range" min="1" max="2.5" step=".05" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/><span>{zoom.toFixed(2)}×</span></label><button type="button" onClick={uploadAll} disabled={busy}>{busy?"Mengunggah…":`✓ Simpan ${files.length} Foto`}</button></div><div className="upload-preview-grid">{files.map((x,i)=><div className="upload-preview" key={i}><div className={`crop-frame ratio-${ratio.replace(":","x")}`}><img src={x.preview} alt={`Preview ${i+1}`}/></div><small>{x.file.name}</small></div>)}</div></>}</div>}

function SitePreview({profile,settings}){return <aside className="live-preview card site-preview"><div className="preview-head"><span>Website</span><strong>Preview Tampilan</strong></div><div className="site-preview-shell"><header><img src={logoUrl} alt="Logo"/><div><strong>{profile.name||"Yayasan Bina Tandang Nurul Falah"}</strong><small>{profile.tagline||"Membina Generasi Qurani, Berilmu, dan Berakhlak Mulia"}</small></div></header><nav>{(settings.navigation||[]).slice(0,6).map((n,i)=><span key={i}>{n.label||"Menu"}</span>)}</nav><div className="site-preview-hero"><small>YAYASAN • PENDIDIKAN ISLAM</small><h3>{profile.name||"Yayasan Bina Tandang Nurul Falah"}</h3><p>{profile.short_description||"Deskripsi singkat yayasan akan tampil di sini."}</p><button>{settings.cta?.primary_label||"Kenal Lebih Dekat"} →</button></div></div></aside>}

function App(){
 const[session,setSession]=useState(null),[admin,setAdmin]=useState(null),[message,setMessage]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[tab,setTab]=useState("dashboard"),[saving,setSaving]=useState(false),[resetMode,setResetMode]=useState(false);
 const[articles,setArticles]=useState([]),[announcements,setAnnouncements]=useState([]),[profile,setProfile]=useState(emptyProfile),[profileId,setProfileId]=useState(null),[articleCats,setArticleCats]=useState([]),[programCats,setProgramCats]=useState([]),[eventCats,setEventCats]=useState([]),[programs,setPrograms]=useState([]),[events,setEvents]=useState([]),[albums,setAlbums]=useState([]),[media,setMedia]=useState([]),[settings,setSettings]=useState({navigation:[],cta:{primary_label:"Kenal Lebih Dekat",primary_href:"#profil"}});
 const[article,setArticle]=useState(emptyArticle),[announcement,setAnnouncement]=useState(emptyAnnouncement),[program,setProgram]=useState(emptyProgram),[event,setEvent]=useState(emptyEvent),[album,setAlbum]=useState(emptyAlbum),[editing,setEditing]=useState(null),[albumId,setAlbumId]=useState(null),[uploading,setUploading]=useState(false);
 const mediaForAlbum=useMemo(()=>media.filter(x=>x.album_id===albumId),[media,albumId]);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>check(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((ev,s)=>{if(ev==="SIGNED_OUT"){setSession(null);setAdmin(false)}else if(s)check(s)});return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session&&admin)load()},[session,admin]);
 async function check(s){if(!s){setSession(null);setAdmin(false);return}const{data,error}=await supabase.rpc("is_admin");if(error||data!==true){await supabase.auth.signOut({scope:"local"});setMessage(error?.message||"Akun bukan admin.");setAdmin(false);return}setSession(s);setAdmin(true)}
 async function load(){const q=await Promise.all([supabase.from("articles").select("*").order("created_at",{ascending:false}),supabase.from("announcements").select("*").order("created_at",{ascending:false}),supabase.from("foundation_profile").select("*").order("updated_at",{ascending:false}).limit(1),supabase.from("article_categories").select("*").order("name"),supabase.from("program_categories").select("*").order("name"),supabase.from("event_categories").select("*").order("name"),supabase.from("programs").select("*").order("order_index"),supabase.from("events").select("*").order("start_at"),supabase.from("gallery_albums").select("*").order("created_at",{ascending:false}),supabase.from("gallery_media").select("*").order("order_index").order("created_at",{ascending:false}),supabase.from("site_settings").select("setting_key,setting_value")]);const bad=q.find(x=>x.error);if(bad){setMessage(bad.error.message);return}setArticles(q[0].data||[]);setAnnouncements(q[1].data||[]);if(q[2].data?.[0]){setProfileId(q[2].data[0].id);setProfile({...emptyProfile,...q[2].data[0],social_links:JSON.stringify(q[2].data[0].social_links||{},null,2)})}setArticleCats(q[3].data||[]);setProgramCats(q[4].data||[]);setEventCats(q[5].data||[]);setPrograms(q[6].data||[]);setEvents(q[7].data||[]);setAlbums(q[8].data||[]);setMedia(q[9].data||[]);const s={navigation:[],cta:{primary_label:"Kenal Lebih Dekat",primary_href:"#profil"}};(q[10].data||[]).forEach(x=>{if(x.setting_key==="navigation")s.navigation=x.setting_value?.items||[];if(x.setting_key==="cta")s.cta=x.setting_value||s.cta});setSettings(s)}
 async function login(e){e.preventDefault();const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message)}
 async function reset(e){e.preventDefault();const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});setMessage(error?.message||"Link reset password sudah dikirim.")}
 async function upload(file,prefix,ratio="16:9",zoom=1){if(!file)return null;if(!imageTypes.includes(file.type)||file.size>12*1024*1024){setMessage("Foto harus JPG/PNG/WEBP/GIF dan maksimal 12 MB.");return null}setUploading(true);try{const cropped=await cropImage(file,ratio,zoom),path=`${session.user.id}/${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}.webp`,res=await supabase.storage.from("MediaArtikel").upload(path,cropped,{contentType:"image/webp",upsert:false});if(res.error)throw res.error;return supabase.storage.from("MediaArtikel").getPublicUrl(path).data.publicUrl}catch(e){setMessage(e.message||"Gagal upload foto");return null}finally{setUploading(false)}}
 async function save(table,data,id,setter,empty){setSaving(true);const payload={...data,updated_at:new Date().toISOString()};delete payload.id;delete payload.created_at;let res=id?await supabase.from(table).update(payload).eq("id",id):await supabase.from(table).insert(payload);setSaving(false);if(res.error){setMessage(res.error.message);return}setter(empty);setEditing(null);await load();setMessage("Berhasil disimpan.")}
 async function remove(table,id){if(!confirm("Hapus data ini?"))return;const{error}=await supabase.from(table).delete().eq("id",id);if(error)setMessage(error.message);else{await load();setMessage("Data dihapus.")}}
 async function saveSetting(key,value){const{error}=await supabase.from("site_settings").upsert({setting_key:key,setting_value:value,updated_at:new Date().toISOString()},{onConflict:"setting_key"});if(error)setMessage(error.message);else{await load();setMessage("Pengaturan tersimpan.")}}
 async function addGalleryFile(url,caption){if(!albumId)return;const{error}=await supabase.from("gallery_media").insert({album_id:albumId,media_type:"image",media_url:url,caption,order_index:mediaForAlbum.length});if(error)setMessage(error.message)}
 const edit=(type,x)=>{setEditing(x.id);if(type==="article")setArticle({...x});if(type==="program")setProgram({...x});if(type==="event")setEvent({...x});if(type==="announcement")setAnnouncement({...x,start_date:x.start_date?.slice(0,16)||"",end_date:x.end_date?.slice(0,16)||""});if(type==="album"){setAlbum({...x});setAlbumId(x.id)}};
 if(!session)return <main className="login"><section className="card"><img src={logoUrl} alt="Logo" style={{width:88}}/><h1>{resetMode?"Reset Password":"Admin Yayasan"}</h1><p>Yayasan Bina Tandang Nurul Falah</p>{resetMode?<form onSubmit={reset}><input type="email" placeholder="Email admin" value={email} onChange={e=>setEmail(e.target.value)} required/><button>Kirim Link Reset</button><button type="button" className="secondary" onClick={()=>setResetMode(false)}>Kembali</button></form>:<><form onSubmit={login}><input type="email" placeholder="Email admin" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button>Masuk Dashboard</button></form><button className="secondary" onClick={()=>setResetMode(true)}>Lupa password?</button></>}{message&&<p className="error">{message}</p>}</section></main>;
 const Nav=()=> <nav className="tabs">{[["dashboard","Dashboard"],["profile","Profil"],["programs","Pendidikan"],["events","Agenda"],["gallery","Galeri"],["articles","Artikel"],["announcements","Pengumuman"],["settings","Tampilan"]].map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}<button className="secondary public-view" onClick={()=>location.href=publicUrl}>Website ↗</button></nav>;
 const List=({items,title,type,render})=><section className="card list"><div className="list-heading"><div><h2>{title}</h2><p>{items.length} item</p></div></div>{items.length?items.map(x=><article className="list-item" key={x.id}><div className="list-main">{render(x)}</div><div className="actions"><button onClick={()=>edit(type,x)}>Edit</button><button className="danger" onClick={()=>remove(type==="article"?"articles":type==="program"?"programs":type==="event"?"events":type==="announcement"?"announcements":"gallery_albums",x.id)}>Hapus</button></div></article>):<p>Belum ada data.</p>}</section>;
 return <main className="admin-page"><header className="admin-header"><div className="admin-brand"><img src={logoUrl} alt="Logo"/><div><h1>Dashboard CMS</h1><p>Kelola website tanpa menyentuh kode</p></div></div><button onClick={()=>supabase.auth.signOut()}>Keluar</button></header>{message&&<div className="notice">{message}</div>}{uploading&&<div className="notice">Memproses foto…</div>}<Nav/>
 {tab==="dashboard"&&<><section className="stats"><div className="card"><strong>{articles.length}</strong><span>Artikel</span></div><div className="card"><strong>{programs.length}</strong><span>Program</span></div><div className="card"><strong>{events.length}</strong><span>Agenda</span></div><div className="card"><strong>{media.length}</strong><span>Foto</span></div></section><section className="card quick-help"><h2>Mulai dari sini</h2><p>Alur sederhana: <b>isi → upload foto → crop → lihat preview → simpan → terbitkan.</b></p><div className="actions"><button onClick={()=>setTab("articles")}>Tulis Artikel</button><button onClick={()=>setTab("programs")}>Tambah Program</button><button onClick={()=>setTab("events")}>Tambah Agenda</button><button onClick={()=>setTab("gallery")}>Kelola Galeri</button></div></section></>}
 {tab==="profile"&&<div className="editor-preview"><section className="card editor"><h2>Profil Yayasan</h2><p className="form-help">Data resmi yayasan yang tampil di profil dan footer. Lihat preview di samping sebelum menyimpan.</p><form onSubmit={e=>{e.preventDefault();let p={...profile};try{p.social_links=JSON.parse(p.social_links||"{}")}catch{setMessage("Media sosial belum berupa JSON yang valid.");return}save("foundation_profile",p,profileId,setProfile,emptyProfile)}}>{[["name","Nama yayasan"],["tagline","Tagline"],["address","Alamat"],["phone","Telepon"],["email","Email"]].map(([k,l])=><label key={k}>{l}<input value={profile[k]||""} onChange={e=>setProfile({...profile,[k]:e.target.value})} required={k==="name"||k==="email"}/></label>)}{[["short_description","Deskripsi singkat",4],["full_description","Deskripsi lengkap",8],["vision","Visi",4],["mission","Misi",6]].map(([k,l,r])=><label key={k}>{l}<textarea rows={r} value={profile[k]||""} onChange={e=>setProfile({...profile,[k]:e.target.value})}/></label>)}<label>Media sosial <small>Masukkan JSON Instagram/Facebook/YouTube/WhatsApp</small><textarea rows="5" value={profile.social_links} onChange={e=>setProfile({...profile,social_links:e.target.value})}/></label><button disabled={saving}>Simpan Profil</button></form></section><SitePreview profile={profile} settings={settings}/></div>}
 {tab==="programs"&&<><div className="editor-preview"><section className="card editor"><h2>{editing?"Edit Program":"Tambah Program Pendidikan"}</h2><p className="form-help">Lengkapi isi, upload foto, crop, lalu cek preview.</p><form onSubmit={e=>{e.preventDefault();save("programs",program,editing,setProgram,emptyProgram)}}><label>Nama program<input placeholder="Tahfiz Al-Qur'an" value={program.title} onChange={e=>setProgram({...program,title:e.target.value})} required/></label><label>Slug<input placeholder="tahfiz-al-quran" value={program.slug} onChange={e=>setProgram({...program,slug:e.target.value})} required/></label><label>Kategori<select value={program.category_id||""} onChange={e=>setProgram({...program,category_id:e.target.value})}><option value="">Pilih kategori</option>{programCats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Deskripsi singkat<input value={program.short_description} onChange={e=>setProgram({...program,short_description:e.target.value})}/></label><label>Detail<textarea rows="8" value={program.content} onChange={e=>setProgram({...program,content:e.target.value})}/></label><ImageField label="Foto program" value={program.image_url} onChange={u=>setProgram({...program,image_url:u})} upload={upload}/><label className="check"><input type="checkbox" checked={program.is_featured} onChange={e=>setProgram({...program,is_featured:e.target.checked})}/> Program unggulan</label><label className="check"><input type="checkbox" checked={program.is_active} onChange={e=>setProgram({...program,is_active:e.target.checked})}/> Tampilkan di website</label><button disabled={saving}>Simpan Program</button>{editing&&<button type="button" className="secondary" onClick={()=>{setEditing(null);setProgram(emptyProgram)}}>Batal</button>}</form></section><Preview title={program.title} image={program.image_url} subtitle="Program Pendidikan" content={program.short_description||program.content} type="Preview Program"/></div><List items={programs} title="Daftar Program" type="program" render={x=><><h3>{x.title}</h3><p>{x.short_description||"Tanpa deskripsi"} · {x.is_active?"Tampil":"Disembunyikan"}</p></>}/></>}
 {tab==="events"&&<><div className="editor-preview"><section className="card editor"><h2>{editing?"Edit Agenda":"Tambah Agenda Kegiatan"}</h2><form onSubmit={e=>{e.preventDefault();save("events",event,editing,setEvent,emptyEvent)}}><label>Nama kegiatan<input value={event.title} onChange={e=>setEvent({...event,title:e.target.value})} required/></label><label>Slug<input value={event.slug} onChange={e=>setEvent({...event,slug:e.target.value})} required/></label><label>Kategori<select value={event.category_id||""} onChange={e=>setEvent({...event,category_id:e.target.value})}><option value="">Pilih kategori</option>{eventCats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Lokasi<input value={event.location} onChange={e=>setEvent({...event,location:e.target.value})}/></label><label>Mulai<input type="datetime-local" value={event.start_at?.slice(0,16)||""} onChange={e=>setEvent({...event,start_at:e.target.value})} required/></label><label>Selesai<input type="datetime-local" value={event.end_at?.slice(0,16)||""} onChange={e=>setEvent({...event,end_at:e.target.value})}/></label><label>Deskripsi<textarea rows="7" value={event.description} onChange={e=>setEvent({...event,description:e.target.value})}/></label><ImageField label="Foto agenda" value={event.image_url} onChange={u=>setEvent({...event,image_url:u})} ratio="4:3" upload={upload}/><label className="check"><input type="checkbox" checked={event.is_published} onChange={e=>setEvent({...event,is_published:e.target.checked})}/> Terbitkan</label><button disabled={saving}>Simpan Agenda</button>{editing&&<button type="button" className="secondary" onClick={()=>{setEditing(null);setEvent(emptyEvent)}}>Batal</button>}</form></section><Preview title={event.title} image={event.image_url} subtitle={event.location||"Agenda Yayasan"} content={event.description} type="Preview Agenda" meta={event.start_at?new Date(event.start_at).toLocaleString("id-ID"):""}/></div><List items={events} title="Daftar Agenda" type="event" render={x=><><h3>{x.title}</h3><p>{x.location||"Lokasi belum diisi"} · {x.is_published?"Terbit":"Draft"}</p></>}/></>}
 {tab==="articles"&&<><div className="editor-preview"><section className="card editor"><h2>{editing?"Edit Artikel":"Tulis Artikel"}</h2><p className="form-help">Tulis artikel, upload cover, crop, lalu lihat preview sebelum terbit.</p><form onSubmit={e=>{e.preventDefault();save("articles",article,editing,setArticle,emptyArticle)}}><label>Judul<input value={article.title} onChange={e=>setArticle({...article,title:e.target.value})} required/></label><label>Slug<input value={article.slug} onChange={e=>setArticle({...article,slug:e.target.value})} required/></label><label>Kategori<select value={article.category_id||""} onChange={e=>setArticle({...article,category_id:e.target.value})}><option value="">Pilih kategori</option>{articleCats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Ringkasan<input value={article.subtitle} onChange={e=>setArticle({...article,subtitle:e.target.value})}/></label><ImageField label="Foto cover artikel" value={article.cover_image_url} onChange={u=>setArticle({...article,cover_image_url:u})} upload={upload}/><label>Isi artikel<textarea rows="18" value={article.content} onChange={e=>setArticle({...article,content:e.target.value})} required/></label><label>Referensi<textarea rows="4" value={article.references_text} onChange={e=>setArticle({...article,references_text:e.target.value})}/></label><label>Status<select value={article.status} onChange={e=>setArticle({...article,status:e.target.value})}><option value="draft">Simpan sebagai Draft</option><option value="published">Terbitkan</option></select></label><button disabled={saving}>Simpan Artikel</button>{editing&&<button type="button" className="secondary" onClick={()=>{setEditing(null);setArticle(emptyArticle)}}>Batal</button>}</form></section><Preview title={article.title} image={article.cover_image_url} subtitle={article.subtitle||"Artikel Yayasan"} content={article.content} type="Preview Artikel"/></div><List items={articles} title="Daftar Artikel" type="article" render={x=><><h3>{x.title}</h3><p>{x.status==="published"?"Terbit":"Draft"} · {x.subtitle||"Tanpa ringkasan"}</p></>}/></>}
 {tab==="announcements"&&<><div className="editor-preview"><section className="card editor"><h2>{editing?"Edit Pengumuman":"Tambah Pengumuman"}</h2><form onSubmit={e=>{e.preventDefault();save("announcements",announcement,editing,setAnnouncement,emptyAnnouncement)}}><label>Judul<input value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})} required/></label><label>Isi<textarea rows="8" value={announcement.content} onChange={e=>setAnnouncement({...announcement,content:e.target.value})}/></label><label>Tipe<select value={announcement.type} onChange={e=>setAnnouncement({...announcement,type:e.target.value})}><option value="text">Teks</option><option value="banner">Banner</option></select></label><ImageField label="Banner pengumuman" value={announcement.banner_image_url} onChange={u=>setAnnouncement({...announcement,banner_image_url:u})} upload={upload}/><label>Mulai tampil<input type="datetime-local" value={announcement.start_date||""} onChange={e=>setAnnouncement({...announcement,start_date:e.target.value})}/></label><label>Selesai tampil<input type="datetime-local" value={announcement.end_date||""} onChange={e=>setAnnouncement({...announcement,end_date:e.target.value})}/></label><label className="check"><input type="checkbox" checked={announcement.is_active} onChange={e=>setAnnouncement({...announcement,is_active:e.target.checked})}/> Aktif</label><button disabled={saving}>Simpan Pengumuman</button></form></section><Preview title={announcement.title} image={announcement.banner_image_url} subtitle="Pengumuman" content={announcement.content} type="Preview Pengumuman"/></div><List items={announcements} title="Daftar Pengumuman" type="announcement" render={x=><><h3>{x.title}</h3><p>{x.type} · {x.is_active?"Aktif":"Nonaktif"}</p></>}/></>}
 {tab==="gallery"&&<><div className="editor-preview"><section className="card editor"><h2>{editing?"Edit Album":"Buat Album Galeri"}</h2><p className="form-help">Buat album, pilih cover, simpan, lalu upload foto dengan preview sebelum diterbitkan.</p><form onSubmit={e=>{e.preventDefault();save("gallery_albums",album,editing,setAlbum,emptyAlbum)}}><label>Nama album<input value={album.title} onChange={e=>setAlbum({...album,title:e.target.value})} required/></label><label>Slug<input value={album.slug} onChange={e=>setAlbum({...album,slug:e.target.value})} required/></label><label>Deskripsi<textarea rows="4" value={album.description} onChange={e=>setAlbum({...album,description:e.target.value})}/></label><ImageField label="Foto cover album" value={album.cover_image_url} onChange={u=>setAlbum({...album,cover_image_url:u})} ratio="4:3" upload={upload}/><label className="check"><input type="checkbox" checked={album.is_published} onChange={e=>setAlbum({...album,is_published:e.target.checked})}/> Tampilkan album</label><button disabled={saving}>Simpan Album</button>{editing&&<button type="button" className="secondary" onClick={()=>{setEditing(null);setAlbum(emptyAlbum)}}>Batal</button>}</form></section><Preview title={album.title} image={album.cover_image_url} subtitle="Galeri Kegiatan" content={album.description} type="Preview Album" meta={albumId?`${mediaForAlbum.length} foto di album`:"Album baru"}/></div><section className="card editor"><div className="list-heading"><div><h2>Foto di Album</h2><p>Pilih album terlebih dahulu. Foto yang dipilih akan tampil di preview sebelum upload.</p></div></div><label>Pilih album<select value={albumId||""} onChange={e=>setAlbumId(e.target.value||null)}><option value="">Pilih album</option>{albums.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label>{albumId?<><GalleryUploader upload={upload} onAdded={addGalleryFile}/><div className="thumbnail-grid">{mediaForAlbum.map(m=><div className="thumb" key={m.id}><img src={m.media_url} alt={m.caption||""}/><div><small>{m.caption||"Foto galeri"}</small><button type="button" className="danger" onClick={()=>remove("gallery_media",m.id)}>Hapus</button></div></div>)}</div></>:<div className="empty-upload"><span>📷</span><strong>Pilih album untuk mulai upload foto</strong><small>Setelah album dipilih, tombol upload akan muncul di sini.</small></div>}</section><List items={albums} title="Daftar Album" type="album" render={x=><><h3>{x.title}</h3><p>{media.filter(m=>m.album_id===x.id).length} foto · {x.is_published?"Tampil":"Disembunyikan"}</p></>}/></>}
 {tab==="settings"&&<div className="editor-preview"><section className="card editor"><h2>Tampilan, Navigasi & CTA</h2><p className="form-help">Gunakan form visual. Perubahan dapat dilihat di preview sebelum disimpan.</p><h3>Menu navigasi</h3>{settings.navigation.map((n,i)=><div className="setting-row" key={`${i}-${n.label}`}><input placeholder="Label menu" value={n.label||""} onChange={e=>{const a=[...settings.navigation];a[i]={...a[i],label:e.target.value};setSettings({...settings,navigation:a})}}/><input placeholder="Link, contoh #profil" value={n.href||""} onChange={e=>{const a=[...settings.navigation];a[i]={...a[i],href:e.target.value};setSettings({...settings,navigation:a})}}/><button type="button" className="danger" onClick={()=>setSettings({...settings,navigation:settings.navigation.filter((_,j)=>j!==i)})}>Hapus</button></div>)}<div className="actions"><button type="button" onClick={()=>setSettings({...settings,navigation:[...settings.navigation,{label:"Menu Baru",href:"#"}]})}>+ Tambah Menu</button><button type="button" onClick={()=>saveSetting("navigation",{items:settings.navigation})}>Simpan Navigasi</button></div><hr/><h3>Tombol utama</h3><label>Teks tombol<input value={settings.cta.primary_label||""} onChange={e=>setSettings({...settings,cta:{...settings.cta,primary_label:e.target.value}})}/></label><label>Tujuan tombol<input value={settings.cta.primary_href||""} onChange={e=>setSettings({...settings,cta:{...settings.cta,primary_href:e.target.value}})}/></label><button type="button" onClick={()=>saveSetting("cta",settings.cta)}>Simpan CTA</button></section><SitePreview profile={profile} settings={settings}/></div>}
 </main>;
}

createRoot(document.getElementById("root")).render(<App/>);
