import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './style.css';

const supabaseUrl=import.meta.env.VITE_SUPABASE_URL;
const supabaseKey=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;
const adminEmail='binatandangnurulfalah.official@gmail.com';

function Login({onLogin}){const [email,setEmail]=useState(adminEmail),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
async function submit(e){e.preventDefault();setError('');if(!supabase){setError('Konfigurasi Supabase belum tersedia.');return}setLoading(true);const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(error.message);setLoading(false);return}const {data:row}=await supabase.from('admins').select('user_id,full_name').eq('user_id',data.user.id).maybeSingle();if(!row){await supabase.auth.signOut();setError('Akun ini belum memiliki akses admin.');setLoading(false);return}onLogin(data.user,row);}
return <main className="center"><form className="card login" onSubmit={submit}><div className="mark">BNF</div><h1>Admin Yayasan</h1><p>Yayasan Bina Tandang Nurul Falah</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{error&&<div className="error">{error}</div>}<button disabled={loading}>{loading?'Masuk…':'Masuk ke Dashboard'}</button></form></main>}

function Dashboard({user,onLogout}){const [stats,setStats]=useState({articles:0,published:0,announcements:0});useEffect(()=>{async function load(){const [a,p,n]=await Promise.all([supabase.from('articles').select('*',{count:'exact',head:true}),supabase.from('articles').select('*',{count:'exact',head:true}).eq('status','published'),supabase.from('announcements').select('*',{count:'exact',head:true}).eq('is_active',true)]);setStats({articles:a.count||0,published:p.count||0,announcements:n.count||0})}load()},[]);return <div className="app"><header><div><strong>BNF CMS</strong><span>Yayasan Bina Tandang Nurul Falah</span></div><div className="user">{user.email}<button className="ghost" onClick={onLogout}>Keluar</button></div></header><section className="hero"><h1>Dashboard Admin</h1><p>Kelola konten website yayasan dari satu tempat.</p></section><section className="grid"><div className="stat"><small>Total Artikel</small><b>{stats.articles}</b></div><div className="stat"><small>Artikel Terbit</small><b>{stats.published}</b></div><div className="stat"><small>Pengumuman Aktif</small><b>{stats.announcements}</b></div></section><section className="card"><h2>Modul CMS</h2><div className="modules"><div><b>Profil Yayasan</b><p>Identitas, visi, misi, kontak dan sosial media.</p></div><div><b>Artikel</b><p>Buat draft, terbitkan artikel dan kelola media.</p></div><div><b>Pengumuman</b><p>Kelola teks berjalan dan banner informasi.</p></div><div><b>Tampilan</b><p>Logo, favicon, warna dan pengaturan halaman.</p></div></div></section></div>}

function App(){const [session,setSession]=useState(null);useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>{if(data.session)verify(data.session.user)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>{if(s)verify(s.user);else setSession(null)});return()=>data.subscription.unsubscribe()},[]);async function verify(user){const {data}=await supabase.from('admins').select('user_id,full_name').eq('user_id',user.id).maybeSingle();if(data)setSession({user,row:data});else await supabase.auth.signOut()}async function logout(){await supabase.auth.signOut()}return session?<Dashboard user={session.user} onLogout={logout}/>:<Login onLogin={(user,row)=>setSession({user,row})}/>}

createRoot(document.getElementById('root')).render(<App/>);
