import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { createClient } from "@supabase/supabase-js";
import "./style.css";
import "./enhancements.css";

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
const logoUrl = `${import.meta.env.BASE_URL}logo-yayasan.svg`;
const foundationName = "Yayasan Bina Tandang Nurul Falah";
const formatDate = (date) => new Intl.DateTimeFormat("id-ID", { day: "numeric", month: "long", year: "numeric" }).format(new Date(date));

function PublicSite() {
  const [profile,setProfile]=useState(null),[articles,setArticles]=useState([]),[announcements,setAnnouncements]=useState([]),[programs,setPrograms]=useState([]),[events,setEvents]=useState([]),[albums,setAlbums]=useState([]),[media,setMedia]=useState([]),[categories,setCategories]=useState([]);
  const [loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState(null),[menuOpen,setMenuOpen]=useState(false),[query,setQuery]=useState(""),[category,setCategory]=useState("all");
  useEffect(()=>{const slug=new URLSearchParams(window.location.search).get("artikel"); Promise.all([
    supabase.from("foundation_profile").select("*").order("updated_at",{ascending:false}).limit(1),
    supabase.from("articles").select("id,title,subtitle,slug,content,cover_image_url,references_text,published_at,created_at,category_id").eq("status","published").order("published_at",{ascending:false}),
    supabase.from("article_categories").select("id,name,slug").order("name"),
    supabase.from("announcements").select("id,title,content,type,banner_image_url,is_active,start_date,end_date,created_at").eq("is_active",true).order("created_at",{ascending:false}),
    supabase.from("programs").select("id,title,slug,short_description,content,image_url,is_featured,order_index,program_categories(name,slug)").eq("is_active",true).order("order_index"),
    supabase.from("events").select("id,title,slug,description,location,start_at,end_at,image_url,event_categories(name,slug)").eq("is_published",true).order("start_at"),
    supabase.from("gallery_albums").select("id,title,slug,description,cover_image_url").eq("is_published",true).order("created_at",{ascending:false}),
    supabase.from("gallery_media").select("id,album_id,media_type,media_url,caption,order_index").order("order_index")
  ]).then(([p,a,c,n,pr,e,g,m])=>{const bad=[p,a,c,n,pr,e,g,m].find(x=>x.error);if(bad)throw bad.error;const aa=a.data||[];setProfile(p.data?.[0]||null);setArticles(aa);setCategories(c.data||[]);setAnnouncements(n.data||[]);setPrograms(pr.data||[]);setEvents(e.data||[]);setAlbums(g.data||[]);setMedia(m.data||[]);if(slug)setSelected(aa.find(x=>x.slug===slug)||null)}).catch(e=>setError(e.message||"Gagal memuat website.")).finally(()=>setLoading(false))},[]);
  const goArticle=(a)=>{history.pushState({},"",`?artikel=${encodeURIComponent(a.slug)}`);setSelected(a);setMenuOpen(false);scrollTo({top:0,behavior:"smooth"})};
  const goHome=()=>{history.pushState({},"",location.pathname);setSelected(null);setMenuOpen(false);scrollTo({top:0,behavior:"smooth"})};
  const filtered=useMemo(()=>articles.filter(a=>(!query||`${a.title} ${a.subtitle||""} ${a.content||""}`.toLowerCase().includes(query.toLowerCase()))&&(category==="all"||a.category_id===category)),[articles,query,category]);
  const social=profile?.social_links&&typeof profile.social_links==="object"?Object.entries(profile.social_links).filter(([,v])=>v):[]; const name=profile?.name||foundationName;
  if(loading)return <main className="site-state"><span className="spinner"/><p>Memuat informasi yayasan…</p></main>;
  if(error)return <main className="site-state"><div className="state-card"><p className="eyebrow">TERJADI KENDALA</p><h1>Website belum dapat dimuat</h1><p>{error}</p><button className="button button-primary" onClick={()=>location.reload()}>Coba lagi</button></div></main>;
  return <div className="site-shell"><a className="skip-link" href="#content">Lewati ke konten utama</a><header className="site-header"><div className="site-header-inner"><button className="site-brand" onClick={goHome}><img src={logoUrl} alt="" className="brand-logo"/><span><strong>{name}</strong><small>{profile?.tagline||"Membina generasi Qurani, berilmu, dan berakhlak mulia"}</small></span></button><button className="menu-toggle" aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>☰ <span>{menuOpen?"Tutup":"Menu"}</span></button><nav className={`site-nav ${menuOpen?"is-open":""}`}><a href="#profil">Profil</a><a href="#pendidikan">Pendidikan</a><a href="#kegiatan">Kegiatan</a><a href="#galeri">Galeri</a><a href="#artikel">Artikel</a><a href="#pengumuman">Pengumuman</a><a href="#kontak">Kontak</a></nav></div></header>
  {announcements[0]&&<aside className="announcement-strip"><div><span className="announcement-label">Informasi terbaru</span><p>{announcements[0].content||announcements[0].title}</p><a href="#pengumuman">Lihat semua →</a></div></aside>}
  {selected?<main className="article-page" id="content"><button className="text-button" onClick={goHome}>← Kembali</button><article className="article-detail"><p className="eyebrow">ARTIKEL YAYASAN</p><h1>{selected.title}</h1>{selected.subtitle&&<p className="article-lead">{selected.subtitle}</p>}<p className="article-date">Dipublikasikan {formatDate(selected.published_at||selected.created_at)}</p>{selected.cover_image_url&&<img src={selected.cover_image_url} className="article-cover" alt=""/>}<div className="article-content">{selected.content.split(/\n+/).map((p,i)=><p key={i}>{p}</p>)}</div>{selected.references_text&&<aside className="references"><h2>Referensi</h2><p>{selected.references_text}</p></aside>}</article></main>:<main id="content"><section className="hero"><div className="hero-inner"><div className="hero-copy"><p className="eyebrow">PENDIDIKAN ISLAM · YAYASAN</p><h1>{name}</h1><p>{profile?.short_description||"Membina generasi Qurani, berilmu, berakhlak mulia, mandiri, dan bermanfaat bagi umat."}</p><div className="hero-actions"><a className="button button-light" href="#profil">Kenal lebih dekat →</a><a className="button button-ghost" href="#pendidikan">Program pendidikan</a></div></div><div className="hero-emblem"><div><img src={logoUrl} alt={`Logo ${name}`}/></div></div></div><div className="hero-metrics"><div><strong>{programs.length}</strong><span>Program pendidikan</span></div><div><strong>{events.length}</strong><span>Agenda mendatang</span></div><div><strong>{articles.length}</strong><span>Artikel terbit</span></div></div></section>
  <div className="content-container"><section id="profil" className="content-section profile-section"><div className="section-intro"><p className="eyebrow">TENTANG KAMI</p><h2>Menumbuhkan generasi Qurani melalui pendidikan dan pembinaan.</h2></div><div className="profile-copy"><p>{profile?.full_description||profile?.short_description||"Profil yayasan akan ditampilkan di sini."}</p>{profile?.address&&<p className="contact-line">⌖ <strong>Alamat</strong> {profile.address}</p>}</div><div className="value-grid"><article className="value-card"><p className="eyebrow">ARAH KAMI</p><h3>Visi</h3><p>{profile?.vision||"—"}</p></article><article className="value-card"><p className="eyebrow">LANGKAH KAMI</p><h3>Misi</h3><p>{profile?.mission||"—"}</p></article></div></section>
  <section id="pendidikan" className="content-section"><div className="section-heading"><div><p className="eyebrow">PENDIDIKAN ISLAM</p><h2>Program yang membina ilmu, iman, dan akhlak.</h2></div><p>Program dapat dikembangkan sesuai kebutuhan yayasan dan peserta didik.</p></div>{programs.length?<div className="feature-grid">{programs.map(p=><article className="feature-card" key={p.id}>{p.image_url&&<img src={p.image_url} alt=""/>}<p className="eyebrow">{p.program_categories?.name||"PROGRAM"}</p><h3>{p.title}</h3><p>{p.short_description}</p></article>)}</div>:<div className="empty-state"><h3>Program segera hadir</h3><p>Program pendidikan akan ditampilkan di sini.</p></div>}</section>
  <section id="kegiatan" className="content-section"><div className="section-heading"><div><p className="eyebrow">AGENDA</p><h2>Kegiatan yayasan</h2></div><p>Rangkaian kegiatan pendidikan, keislaman, dan sosial.</p></div>{events.length?<div className="event-grid">{events.map(e=><article className="event-card" key={e.id}><div className="event-date"><strong>{new Date(e.start_at).getDate()}</strong><span>{new Intl.DateTimeFormat("id-ID",{month:"short"}).format(new Date(e.start_at))}</span></div><div><p className="eyebrow">{e.event_categories?.name||"KEGIATAN"}</p><h3>{e.title}</h3><p>{e.description}</p><small>{new Date(e.start_at).toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"})} · {e.location||"Lokasi diumumkan kemudian"}</small></div></article>)}</div>:<div className="empty-state"><h3>Belum ada agenda</h3></div>}</section>
  <section id="galeri" className="content-section"><div className="section-heading"><div><p className="eyebrow">DOKUMENTASI</p><h2>Galeri kegiatan</h2></div><p>Dokumentasi pendidikan dan kegiatan yayasan.</p></div>{albums.length?<div className="gallery-grid">{albums.map(a=>{const imgs=media.filter(m=>m.album_id===a.id);const cover=a.cover_image_url||imgs[0]?.media_url;return <article className="gallery-card" key={a.id}>{cover?<img src={cover} alt=""/>:<div className="gallery-placeholder">Bina Tandang Nurul Falah</div>}<div><p className="eyebrow">ALBUM</p><h3>{a.title}</h3><p>{a.description}</p><small>{imgs.length} dokumentasi</small></div></article>})}</div>:<div className="empty-state"><h3>Galeri segera hadir</h3></div>}</section>
  <section id="artikel" className="content-section"><div className="section-heading"><div><p className="eyebrow">PUBLIKASI</p><h2>Artikel & wawasan Islam</h2></div><p>Temukan tulisan tentang pendidikan, Al-Qur’an, akhlak, dan kegiatan yayasan.</p></div><div className="article-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari artikel…" aria-label="Cari artikel"/><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Kategori artikel"><option value="all">Semua kategori</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>{filtered.length?<div className="article-grid">{filtered.map((a,i)=><article className={`article-card ${i===0?"article-card-featured":""}`} key={a.id}>{a.cover_image_url?<img src={a.cover_image_url} alt="" className="article-thumbnail"/>:<div className="article-placeholder"/>}<div className="article-card-body"><p className="article-date">{formatDate(a.published_at||a.created_at)}</p><h3>{a.title}</h3>{a.subtitle&&<p>{a.subtitle}</p>}<button className="text-button" onClick={()=>goArticle(a)}>Baca artikel →</button></div></article>)}</div>:<div className="empty-state"><h3>Artikel tidak ditemukan</h3><p>Coba kata kunci atau kategori lain.</p></div>}</section>
  <section id="pengumuman" className="content-section"><div className="section-heading"><div><p className="eyebrow">INFORMASI</p><h2>Pengumuman yayasan</h2></div></div><div className="announcement-list">{announcements.map(a=><article className="announcement-card" key={a.id}>{a.banner_image_url&&<img src={a.banner_image_url} alt=""/>}<div><p className="eyebrow">{a.type==="banner"?"AGENDA":"INFORMASI"}</p><h3>{a.title}</h3><p>{a.content}</p></div></article>)}</div></section></div></main>}
  <footer id="kontak" className="site-footer"><div className="footer-inner"><div className="footer-brand"><img src={logoUrl} alt=""/><div><strong>{name}</strong><p>{profile?.short_description||"Membina generasi Qurani, berilmu, dan berakhlak mulia."}</p></div></div><div className="footer-contact"><p className="eyebrow">HUBUNGI KAMI</p>{profile?.phone&&<a href={`tel:${profile.phone}`}>{profile.phone}</a>}{profile?.email&&<a href={`mailto:${profile.email}`}>{profile.email}</a>}{social.map(([k,v])=><a href={v} target="_blank" rel="noreferrer" key={k}>{k}</a>)}</div></div><p className="footer-bottom">© {new Date().getFullYear()} {name} · Pendidikan Islam, pembinaan, dan kebermanfaatan.</p></footer></div>
}
createRoot(document.getElementById("root")).render(<PublicSite/>);
